<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign In</name>
   <tag></tag>
   <elementGuidId>b00ea2ae-95bc-4bd3-80dd-3b28e871f474</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='kt_login_signin_submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kt_login_signin_submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>25dcface-3eb8-4eef-a816-608e4e1395aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f891a989-3406-4862-8245-db0c5d71fcc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kt_login_signin_submit</value>
      <webElementGuid>aa5381ca-b56a-41c8-880f-b716c88cd0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary font-weight-bolder font-size-h6 px-30 py-4 my-3 mr-3</value>
      <webElementGuid>2529f194-64f6-4811-a6be-f59539f73102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sign In </value>
      <webElementGuid>1b47446b-4b4f-4ed4-9aa1-427d5713b026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_login_signin_submit&quot;)</value>
      <webElementGuid>6c80705a-f5e7-4c2c-9ad8-448e17056aca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='kt_login_signin_submit']</value>
      <webElementGuid>8b27c603-b90a-4341-a7d9-87f09ea03cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_login_signin_form']/div[4]/button</value>
      <webElementGuid>93b95708-c72a-4615-aa67-a51d9f935a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>06b50d76-8f60-4651-b7b0-0fbc231f2dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username or Email'])[1]/following::button[1]</value>
      <webElementGuid>3267791d-85d4-47f5-90bc-eb78b70b0bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ver. 0.13.666.07211541.548.1.07211509'])[1]/preceding::button[1]</value>
      <webElementGuid>9b52e84b-0ed5-4e00-b5af-d80fa8256ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'kt_login_signin_submit', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>4cdba1f5-c062-48ba-8cb1-5eff8dd6911f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign In']/parent::*</value>
      <webElementGuid>f512957f-7d2e-414c-b8fe-6c08e5515b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>e23e94dd-9655-473f-84f3-cd1f0e809f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'kt_login_signin_submit' and (text() = ' Sign In ' or . = ' Sign In ')]</value>
      <webElementGuid>03d4afbc-d5d9-4cea-bce7-88cbbddd2571</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
