<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_KOMARUDIN</name>
   <tag></tag>
   <elementGuidId>69bfe24d-762a-4936-aaae-d23b80df801a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-header[@id='kt_header']/div/app-topbar/div/div[3]/div[7]/div/div/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.text-dark-50.font-weight-bolder.font-size-base.d-none.d-md-inline.mr-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>04fb8d45-464d-4188-a660-eee690834946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-dark-50 font-weight-bolder font-size-base d-none d-md-inline mr-3</value>
      <webElementGuid>d903e1e0-dd06-4072-a3f9-ac2e36d0be6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KOMARUDIN</value>
      <webElementGuid>b8725cff-d127-4f68-aaeb-8c7586e4ac10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_header&quot;)/div[@class=&quot;d-flex align-items-stretch justify-content-between container-fluid&quot;]/app-topbar[@class=&quot;topbar&quot;]/div[@class=&quot;topbar-menu&quot;]/div[3]/div[7]/div[@class=&quot;ng-star-inserted dropdown&quot;]/div[@class=&quot;dropdown-toggle topbar-item&quot;]/div[@class=&quot;btn btn-icon w-auto btn-clean d-flex align-items-center btn-lg px-2&quot;]/span[@class=&quot;text-dark-50 font-weight-bolder font-size-base d-none d-md-inline mr-3&quot;]</value>
      <webElementGuid>037132b9-e207-41cc-b181-29e352a74cb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-header[@id='kt_header']/div/app-topbar/div/div[3]/div[7]/div/div/div/span[2]</value>
      <webElementGuid>dc6095f2-9c19-45d3-8172-f740a1742fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi,'])[1]/following::span[1]</value>
      <webElementGuid>3e327379-2d37-4bd9-b647-01f95f3afa1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created with Sketch.'])[36]/following::span[2]</value>
      <webElementGuid>77307f4c-023f-4eab-9752-b5c925350cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K'])[1]/preceding::span[1]</value>
      <webElementGuid>777df4bd-3924-4cfd-a2a7-8f67bb7cd80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K'])[2]/preceding::span[3]</value>
      <webElementGuid>7859e055-309b-45b8-b731-a9b5f47de48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KOMARUDIN']/parent::*</value>
      <webElementGuid>8eb56f2b-0c0c-418c-986a-83817153cd9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[2]</value>
      <webElementGuid>637f7a3a-89cb-4bd7-bdb7-399f1dcd70aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'KOMARUDIN' or . = 'KOMARUDIN')]</value>
      <webElementGuid>6ff71b47-5152-4783-95ab-d92f86d6ff97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
