<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_PTKKATALONCASE</name>
   <tag></tag>
   <elementGuidId>9c455659-2d2f-46fe-b5bc-e31aabe6d341</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_content']/div/div/app-warehouse-asset-list/div/table/tbody/tr[3]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c4af3baf-8b15-4e07-88b0-20f6ebec1e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>6e80e930-401d-4130-9948-44a85fbe91eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-cell cdk-cell cdk-column-name mat-column-name ng-star-inserted</value>
      <webElementGuid>4cb387d6-80cd-4fe6-8630-dcf0bf0b8963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PTKKATALONCASE</value>
      <webElementGuid>b04f499d-38e7-4cfc-ac38-a8b2d20cad34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_content&quot;)/div[@class=&quot;d-flex flex-column-fluid ng-star-inserted&quot;]/div[@class=&quot;layout-content container-fluid&quot;]/app-warehouse-asset-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mat-elevation-z8&quot;]/table[@class=&quot;mat-table cdk-table mat-sort&quot;]/tbody[1]/tr[@class=&quot;mat-row cdk-row ng-star-inserted&quot;]/td[@class=&quot;mat-cell cdk-cell cdk-column-name mat-column-name ng-star-inserted&quot;]</value>
      <webElementGuid>f7b4e354-d4b8-4c89-a908-7eeef6adf422</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content']/div/div/app-warehouse-asset-list/div/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>72845829-70c1-468d-bb43-6c69f6feee2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WH-ASSET-PTK-0001'])[1]/following::td[1]</value>
      <webElementGuid>5fd85226-6685-455f-91c4-11590f795729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIVE'])[2]/following::td[2]</value>
      <webElementGuid>753a203e-a47b-45d5-8d60-42269cdaf917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PTK'])[1]/preceding::td[1]</value>
      <webElementGuid>bbf03852-82a1-4371-a5dc-5e9e368ff7ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIVE'])[3]/preceding::td[2]</value>
      <webElementGuid>2e557f70-9343-4ffb-b2d2-877539efdf67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PTKKATALONCASE']/parent::*</value>
      <webElementGuid>f504f8c7-58a1-4ca4-be8b-a9e5af2d70a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]</value>
      <webElementGuid>bf711377-17a1-4855-be93-bdd4257d3088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'PTKKATALONCASE' or . = 'PTKKATALONCASE')]</value>
      <webElementGuid>a6e5d968-1ce2-4594-b685-9ab65855a175</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
