<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_WH-ASSET-PTK-0001</name>
   <tag></tag>
   <elementGuidId>c47acbfa-a3de-431a-a03c-88344cd62851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_content']/div/div/app-warehouse-asset-list/div/table/tbody/tr[3]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f262d045-1a61-4577-a4bc-dfb8308aa666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>556b58a0-5d47-4092-8601-a3eb498ca0b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-cell cdk-cell cdk-column-code mat-column-code ng-star-inserted</value>
      <webElementGuid>2ad67ca4-acf8-40cc-9de4-35799d0a40d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WH-ASSET-PTK-0001</value>
      <webElementGuid>4fb87414-f7ad-45cf-8160-6926d634b000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_content&quot;)/div[@class=&quot;d-flex flex-column-fluid ng-star-inserted&quot;]/div[@class=&quot;layout-content container-fluid&quot;]/app-warehouse-asset-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mat-elevation-z8&quot;]/table[@class=&quot;mat-table cdk-table mat-sort&quot;]/tbody[1]/tr[@class=&quot;mat-row cdk-row ng-star-inserted&quot;]/td[@class=&quot;mat-cell cdk-cell cdk-column-code mat-column-code ng-star-inserted&quot;]</value>
      <webElementGuid>431c7aca-6282-490c-9786-e6ac75caef05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content']/div/div/app-warehouse-asset-list/div/table/tbody/tr[3]/td</value>
      <webElementGuid>07b8682b-9f8c-4678-9ed3-c77955912c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIVE'])[2]/following::td[1]</value>
      <webElementGuid>2793ac19-f90a-46c6-ac1f-5c18488b05c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MKS'])[1]/following::td[2]</value>
      <webElementGuid>613cb0cb-e1be-4f5f-a153-9cab03df844e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PTKKATALONCASE'])[1]/preceding::td[1]</value>
      <webElementGuid>6e28dbfc-44bd-4a7a-887e-e913777a1cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PTK'])[1]/preceding::td[2]</value>
      <webElementGuid>76d4875c-485e-4361-b816-a0f003763863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WH-ASSET-PTK-0001']/parent::*</value>
      <webElementGuid>7d0b5ae1-7f45-4943-8f8e-babbaf92b103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td</value>
      <webElementGuid>3166bd4f-02e0-4589-8217-5b6dba3d2b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'WH-ASSET-PTK-0001' or . = 'WH-ASSET-PTK-0001')]</value>
      <webElementGuid>8ce8fa01-77cf-4925-8af0-b25ba19cbba9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
