<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PONTIANAK</name>
   <tag></tag>
   <elementGuidId>6e6b1f63-d149-4e99-b098-21c0377a917a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-14']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-14 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0acca6fe-3279-451f-9836-3bae28fdff4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>aeb0c670-364b-45a4-818d-c50fe5af0b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> PONTIANAK </value>
      <webElementGuid>e52eaab2-1212-47f0-a72e-d48ebfd3ced5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-14&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>7f5ed8f5-b5ab-4080-aa0b-32a253409186</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-14']/span</value>
      <webElementGuid>471af4d5-c1f0-45b4-bb34-274e4f32c218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PALEMBANG'])[1]/following::span[1]</value>
      <webElementGuid>9f375044-93ee-4928-903b-2aa47cbb910b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIREBON'])[1]/following::span[2]</value>
      <webElementGuid>8284a65d-250b-4c61-aba4-b771c61bae47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEMARANG'])[1]/preceding::span[1]</value>
      <webElementGuid>0174c63c-cfbc-4b8c-87c9-2ae984289cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAMARINDA'])[1]/preceding::span[2]</value>
      <webElementGuid>8cb79d62-5111-4e9e-bc4f-ab664b7305b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PONTIANAK']/parent::*</value>
      <webElementGuid>e3b2a78e-7c38-4543-bcdf-3b803d276c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[12]/span</value>
      <webElementGuid>e95d50e9-87f4-42e3-96f2-587637babaf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' PONTIANAK ' or . = ' PONTIANAK ')]</value>
      <webElementGuid>fc87b14f-8043-4fa7-937e-00169625243b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
