<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_WH-ASSET-PTK-0001</name>
   <tag></tag>
   <elementGuidId>c1e9ce13-b651-4df7-abd6-39ab88c85567</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_content']/div/div/app-warehouse-asset-list/div/table/tbody/tr[3]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f3012797-a9c5-4cff-b12b-84a3d89d2473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>6dcd2a97-8be0-446d-9327-dde8e8d828fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-cell cdk-cell cdk-column-code mat-column-code ng-star-inserted</value>
      <webElementGuid>712ee538-ee32-466a-95a8-c3b092c5b582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WH-ASSET-PTK-0001</value>
      <webElementGuid>8f5e8973-d418-48e7-854b-031736989df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_content&quot;)/div[@class=&quot;d-flex flex-column-fluid ng-star-inserted&quot;]/div[@class=&quot;layout-content container-fluid&quot;]/app-warehouse-asset-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mat-elevation-z8&quot;]/table[@class=&quot;mat-table cdk-table mat-sort&quot;]/tbody[1]/tr[@class=&quot;mat-row cdk-row ng-star-inserted&quot;]/td[@class=&quot;mat-cell cdk-cell cdk-column-code mat-column-code ng-star-inserted&quot;]</value>
      <webElementGuid>a3fa5ffc-b458-4ad3-b7c1-fd4bad0434a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content']/div/div/app-warehouse-asset-list/div/table/tbody/tr[3]/td</value>
      <webElementGuid>dca45edd-b702-4058-8011-a428fe35e817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIVE'])[2]/following::td[1]</value>
      <webElementGuid>a3db0ecd-0aa2-4f0d-84f2-821ece00f8b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MKS'])[1]/following::td[2]</value>
      <webElementGuid>ec732724-8be8-47a7-8ff1-65bab5a0262c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PTKKATALONCASE'])[1]/preceding::td[1]</value>
      <webElementGuid>9ce4bf38-2a90-4847-ab04-021d2622a4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PTK'])[1]/preceding::td[2]</value>
      <webElementGuid>e7f9f63e-555a-40e6-80ee-c2c12f18962d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WH-ASSET-PTK-0001']/parent::*</value>
      <webElementGuid>3750caaf-0743-4e6c-af4e-bfa6265b4c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td</value>
      <webElementGuid>265f1e30-966d-4b90-8ac7-51a0b54c4d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'WH-ASSET-PTK-0001' or . = 'WH-ASSET-PTK-0001')]</value>
      <webElementGuid>47098181-359d-4841-8dea-9ebd1c4a72ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
